objects/Student_Scoring_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <description>Points</description>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <description>Skill</description>
        <globalPicklist>Skills</globalPicklist>
        <label>Skill</label>
        <type>Picklist</type>
    </fields>
    <label>Student Scoring Skill</label>
    <nameField>
        <displayFormat>SK-{00000}</displayFormat>
        <label>Student Scoring Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Scoring Skill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SM_RegisterStudentScoringSkillCX.cls
public with sharing class SM_RegisterStudentScoringSkillCX {
    // procedure constructor
    public SM_RegisterStudentScoringSkillCX(ApexPages.StandardController controller) {

	}

    @RemoteAction
    public static String toRegister ( Boolean  active,
                                      String   skill,
                                      Decimal  points
                                    ) {

        Student_Scoring_Skill__c studentSkills = new Student_Scoring_Skill__c();
        studentSkills.Active__c                = active;
        studentSkills.Skill__c                 = skill;
        studentSkills.Points__c                = points;

        try {
            insert studentSkills;
        } catch ( DmlException ex ) {
            return ex.getMessage();
        }

        return studentSkills.Skill__c;
    }

    @RemoteAction
	public static String getJSONStudents() {
		// serialize to JSON
		return JSON.serialize([SELECT Active__c, Skill__c, Points__c FROM Student_Scoring_Skill__c]);
	}

    @RemoteAction
	public static String getSkillPickList() {
		Schema.DescribeFieldResult fieldSkill = Student_Scoring_Skill__c.Skill__c.getDescribe();
		List<Schema.PicklistEntry> pickListSkill = fieldSkill.getPicklistValues();
		return JSON.serialize(pickListSkill);
    }
}