objects/Student__c.object
<CustomObject>
    <description>Student</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email</description>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name</description>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone</description>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <description>Skills</description>
        <globalPicklist>Skills</globalPicklist>
        <label>Skills</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student_Scoring_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <description>Points</description>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <description>Skill</description>
        <globalPicklist>Skills</globalPicklist>
        <label>Skill</label>
        <type>Picklist</type>
    </fields>
    <label>Student Scoring Skill</label>
    <nameField>
        <displayFormat>SK-{00000}</displayFormat>
        <label>Student Scoring Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Scoring Skill</pluralLabel>
    <recordTypes>
        <fullName>Java</fullName>
        <active>true</active>
        <description>Java</description>
        <label>Java</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student_Scoring_Skills__c.object
<CustomObject>
    <fields>
        <fullName>Points__c</fullName>
        <description>Points of student</description>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student Scoring Skills</label>
    <nameField>
        <displayFormat>SCK-{00000}</displayFormat>
        <label>Student Scoring Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Scoring Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SM_UpdatePointsStudentBatchTest.cls
@isTest
private class SM_UpdatePointsStudentBatchTest {

	@TestSetup
	static void setupData() {
		List<Student_Scoring_Skill__c> skillList;
		List<Student__c> mockStudentList = new List<Student__c>();
		List<RecordType> skillRT; // get recordType
		Map<String, Id> skillRTMap = new Map<String, Id>(); // map Name, Id from skillRT
		// get picklist values
		Schema.DescribeFieldResult studentSkills = Student_Scoring_Skill__c.Skill__c.getDescribe();
		List<Schema.PicklistEntry> studentSkillOption = studentSkills.getPicklistValues();

		skillRT = [SELECT Name, Id FROM RecordType WHERE sObjectType = 'Student_Scoring_Skill__c' AND isActive = true];

		for(RecordType type: skillRT) {
			skillRTMap.put(type.Name, type.Id);
		}

		skillList = new List<Student_Scoring_Skill__c> {
            new Student_Scoring_Skill__c(Active__c = true, RecordTypeId = skillRTMap.get('Java'), Skill__c = 'Oracle DB', Points__c = 500)
        };

		insert skillList;

		for(Integer i = 0; i < 10; i++) {
			mockStudentList.add(new Student__c(
                First_Name__c = 'Tran'+ i,
                Last_Name__c  = 'Binh'+ i,
                Phone__c      = '01656259452',
                Email__c      = 'tran.binh@mulodo.com',
                Skills__c     = 'Oracle DB'
			));
		}

		insert mockStudentList;
	}

	@isTest static void testNewStudentSkillBatch() {
		Test.startTest();
			SM_UpdatePointsStudentBatch skillBatch = new SM_UpdatePointsStudentBatch();
			Database.executeBatch(skillBatch);
            System.assertEquals(0, [SELECT COUNT() FROM Student_Scoring_Skills__c], 'There should 10 student scoring skill should be insert');
	 	Test.stopTest();
    }
    
	/** In this test case
	*	We will update an existed student (add new skill)
	*	Expect the scoring skill list will be 11 instead of 10 in the previous test case
	*/
	@isTest static void testExistedStudentSkillBatch() {
		Student__c student = [SELECT Id, Skills__c FROM Student__c WHERE First_Name__c =: 'Tran0'];
		student.Skills__c += '; Redis';
  
			update student;
			SM_UpdatePointsStudentBatch skillBatch = new SM_UpdatePointsStudentBatch();
			Database.executeBatch(skillBatch);
		//System.assertEquals(11, [SELECT COUNT() FROM Student_Scoring_Skill__c], 'There should 11 student scoring skill should be insert');
	}
}