objects/Student__c.object
<CustomObject>
    <description>Student</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>Fresher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leader</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scores__c</fullName>
        <description>Scores</description>
        <label>Scores</label>
        <summarizedField>Student_Scoring_Skills__c.Points__c</summarizedField>
        <summaryFilterItems>
            <field>Student_Scoring_Skills__c.Points__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Student_Scoring_Skills__c.Student_ID__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SM_LevelStudentBatch.cls
/**
 * Batch update Level for student
 * Created by tran.binh@mulodo.com on 10/31/2017.
 */
public class SM_LevelStudentBatch implements Database.Batchable<sObject>{

	/**
     * start run query on database
     * @param: jobId (type: Database.BatchableContext)
     */
	public System.Iterable<sObject> start(Database.BatchableContext jobId) {
		return [SELECT Scores__c, Level__c FROM Student__c];
	}

	/**
     * execute batch for check condition to  Level of Student__c
     * @param: jobId (type: Database.BatchableContext)
     * @param: listLevel (type: List<sObject>)
     */
	public Void execute(Database.BatchableContext jobId, List<sObject> listLevel) {
		List<Student__c> updateListLevel = new List<Student__c>();
		for(Student__c student: (List<Student__c>)listLevel) {
			if (student.Scores__c >= 400) {
				student.Level__c = 'Leader';
			} else if (student.Scores__c >= 300) {
				student.Level__c = 'Senior';
			} else if (student.Scores__c >= 200) {
				student.Level__c = 'Junior';
			} else if (student.Scores__c >= 0) {
				student.Level__c = 'Fresher';
			}
			updateListLevel.add(student);
		}
		update updateListLevel;
	}

	/**
     * finish run batch
     * @param: jobId (type: Database.BatchableContext)
     */
	public Void finish(Database.BatchableContext jobId) {
	}
}